services:
  robot:
    profiles:
      - robot
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - loop-breakers/robot
      args:
        AGENT: robot
    container_name: robot-agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0
      - /dev/media0:/dev/media0
      - /dev/dma_heap:/dev/dma_heap
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_JID: "alberto-robot@$XMPP_HOST"
      XMPP_PASSWORD: $XMPP_PASSWORD
      LOGGER_JID: "logger@$XMPP_HOST"
    volumes:
      - /run/udev:/run/udev:ro
      - ./:/app

  controller:
    profiles:
      - robot
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - loop-breakers/controller
      args:
        AGENT: controller
    container_name: ctrl-agent
    environment:
      XMPP_JID: "alberto-ctrl@$XMPP_HOST"
      XMPP_PASSWORD: $XMPP_PASSWORD
    volumes:
      - ./:/app

  camera:
    profiles:
      - gateway
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - loop-breakers/camera
      args:
        AGENT: camera
    container_name: camera-agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0
      - /dev/media0:/dev/media0
      - /dev/dma_heap:/dev/dma_heap
    privileged: true
    environment:
      XMPP_JID: "camera@$XMPP_HOST"
      XMPP_PASSWORD: $XMPP_PASSWORD
      CAMERA_WIDTH: 768
      CAMERA_HEIGHT: 432
    volumes:
      - ./:/app

  logger:
    profiles:
      - logger
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - loop-breakers/logger
      args:
        AGENT: logger
    container_name: logger-agent
    environment:
      XMPP_JID: "logger@$XMPP_HOST"
      XMPP_PASSWORD: $XMPP_PASSWORD
    volumes:
      - ./:/app
